# Generated by Django 4.1.6 on 2023-05-25 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=90, null=True)),
                ('type', models.SmallIntegerField(default=10)),
                ('img', models.ImageField(max_length=250, upload_to='%Y%m/swipe')),
                ('order', models.ImageField(default=0, upload_to='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('target_url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'system_swipe',
            },
        ),
        migrations.CreateModel(
            name='ImageRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(max_length=250, upload_to='%Y%m/file')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=models.SET(None), to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(None), related_name='upload_image', to=settings.AUTH_USER_MODEL, verbose_name='upload_user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
