# Generated by Django 4.1.6 on 2023-05-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipe',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='type',
        ),
    ]
