# Generated by Django 4.1.6 on 2023-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_swipe_end_time_remove_swipe_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipe',
            name='desc',
        ),
        migrations.AlterField(
            model_name='swipe',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
