# Generated by Django 4.1.6 on 2023-05-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('system', '0003_remove_swipe_desc_alter_swipe_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerelated',
            name='user',
        ),
        migrations.AlterField(
            model_name='imagerelated',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
