# Generated by Django 4.1.6 on 2023-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_imagerelated_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerelated',
            name='img',
            field=models.ImageField(max_length=250, upload_to='images/%Y%m'),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='img',
            field=models.ImageField(max_length=250, upload_to='swipe/%Y%m'),
        ),
    ]
