# Generated by Django 4.1.6 on 2023-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='expire_data',
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
