# Generated by Django 4.1.6 on 2023-05-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_remove_ticket_expire_data_ticket_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='AttractionInfo',
        ),
    ]
