# Generated by Django 4.1.6 on 2023-05-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_rename_info_attractioninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='info',
        ),
        migrations.AddField(
            model_name='attraction',
            name='desc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attraction.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
