# Generated by Django 4.1.6 on 2023-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0004_remove_attraction_content_remove_ticket_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='open',
        ),
    ]
