# Generated by Django 4.1.6 on 2023-05-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_remove_ticket_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='desc',
        ),
    ]
