# Generated by Django 4.1.6 on 2023-05-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0008_alter_attractioninfo_info_alter_ticketinfo_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='rating',
        ),
    ]
