# Generated by Django 4.1.6 on 2023-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0009_remove_attraction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='banner_img',
            field=models.ImageField(max_length=250, upload_to='attraction/banner_img/%Y%m/'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='cover_img',
            field=models.ImageField(max_length=250, upload_to='attraction/cover_img/%Y%m'),
        ),
    ]
