# Generated by Django 4.1.6 on 2023-05-25 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=32, verbose_name='order number')),
                ('purchase_count', models.IntegerField(default=1, verbose_name='purchase count')),
                ('purchase_amount', models.FloatField(verbose_name='purchase amount')),
                ('full_name', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Submit'), (2, 'Paid'), (3, 'Canceled')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('sn', models.CharField(max_length=32, verbose_name='payment#')),
                ('third_sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='third party payment#')),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('flash_name', models.CharField(max_length=120, verbose_name='item name')),
                ('flash_image', models.ImageField(upload_to='', verbose_name='item image')),
                ('flash_price', models.FloatField(default=0)),
                ('flash_discount', models.FloatField(default=0)),
                ('flash_sell_price', models.FloatField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('status', models.SmallIntegerField(choices=[(1, 'Submit'), (2, 'Paid'), (3, 'Canceled')], default=1)),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='attraction.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
