# Generated by Django 4.1.6 on 2023-05-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remark',
        ),
    ]
