# Generated by Django 4.1.6 on 2023-05-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_date_remove_orderitem_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flash_desc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
