# Generated by Django 4.1.6 on 2023-05-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_flash_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
